title: "Ont-demux Pipeline report"
subtitle: "Best-practice workflow for ONT basecalling and demultiplexing"
custom_logo: "pipelinelogo.png"
custom_logo_title: "ONT basecalling"
custom_logo_url: "http://www.github.com/marchoeppner"
skip_versions_section: true

extra_fn_clean_exts:
    - _R1
    - _R2
    - .NanoStats
    - _duplicate_metrics.txt
    - .pass

report_comment: >
    This report has been generated automatically by marchoeppner/ont-demux.
    For help interpreting the outputs, please see: https://github.com/marchoeppner/ont-demux
report_header_info:
    - Contact E-mail: "mphoeppner@gmail.com"
    - Application Type: "ONT Basecalling"

top_modules:
    - 'general_stats'

report_section_order:
    software_versions:
        order: -1001
